[preferred]
# Use xdg-desktop-portal-gtk for file chooser and settings
default=gtk
# wlroots for screen capture
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
# gnome-keyring for secrets (Bitwarden, app passwords, etc.)
org.freedesktop.impl.portal.Secret=gnome-keyring
# Inhibit doesn't work under wlroots
org.freedesktop.impl.portal.Inhibit=none
